import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Overview sidebar - explicit so Key Concepts can group pages without
  // moving files (URLs stay stable). New overview pages must be added here.
  overviewSidebar: [
    'overview/overview',
    {
      type: 'category',
      label: 'Key Concepts',
      collapsed: false,
      items: [
        'overview/grid',
        'overview/venues',
        'overview/agents',
        'overview/context',
        'overview/skills',
      ],
    },
    'overview/sdk',
    'overview/contribute',
  ],
  
  // User Guide sidebar - for the user-guide section
  userGuideSidebar: [{type: 'autogenerated', dirName: 'user-guide'}],
  
  // Protocol sidebar - for the protocol section
  protocolSidebar: [{type: 'autogenerated', dirName: 'protocol'}],
  
  // Operator Guide sidebar - for the operator-guide section
  operatorGuideSidebar: [{type: 'autogenerated', dirName: 'operator-guide'}],
  
};

export default sidebars;
