import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Overview sidebar - for the overview section
  overviewSidebar: [{type: 'autogenerated', dirName: 'overview'}],
  
  // User Guide sidebar - for the user-guide section
  userGuideSidebar: [{type: 'autogenerated', dirName: 'user-guide'}],
  
  // Protocol sidebar - for the protocol section
  protocolSidebar: [{type: 'autogenerated', dirName: 'protocol'}],
  
  // COGs sidebar - for the cogs section
  cogsSidebar: [
    'cogs-overview',
    {
      type: 'category',
      label: 'COGs',
      items: [{type: 'autogenerated', dirName: 'cogs'}],
    },
  ],
};

export default sidebars;
